// Walkthroughs found by tools/ratkaisija.js, one per level (level number → moves, each held 0.5 s).
// Y = ylös, A = alas, V = vasen, O = oikea, '-' = leaf level, '~' = half tilt.
// Check them with: pisaraSolver.followAll(PISARA_OHJEET)
window.PISARA_OHJEET = {
  1: 'O Y YO~ Y -',
  2: 'YO YO Y -',
  3: 'AV AV AV AO',
  4: 'YO YO Y -',
  5: 'V AV A A -',
  6: 'YO YO AO V YO AV~ A~ YV~ O V O~ - V~ - YV~ YO AO AO A',
  7: 'YO YO YO Y -',
  8: 'A A AO Y Y YV V',
  9: 'YO YO V Y Y -',
  10: 'O AO AO AV - A AV -',
  11: 'V YV Y Y -',
  12: 'AO AO V A AV AV -',
  13: 'YO YO YO Y',
  14: 'AO O A A -',
  15: 'YO Y Y V -',
  16: 'V YV O Y YV YV',
  17: 'AO AO AO A -',
  18: 'YO YV Y Y A - O O -',
  19: 'AO A AO O',
  20: 'YO AO V A AO V AV -',
  21: 'AV AV A -',
  22: 'YO YO Y -',
  23: 'O O YV YO YV O A',
  24: 'YV YV YV Y',
  25: 'AO AO A AO',
  26: 'AO AO A AO',
  27: 'O YO Y Y -',
  28: 'Y AO O Y Y YO YO',
  29: 'AV AV AV A -',
  30: 'YV V Y Y -',
  31: 'YV YV YV Y Y -',
  32: 'YV V Y Y -',
  33: 'AV V - O A - - A V AV A -',
  34: 'V YV Y Y Y',
  35: 'AO AO A AO -',
  36: 'YO O YO Y YO O YO',
  37: 'V YV Y Y -',
  38: 'O YV V Y YO AO - AO YV A AO - YV YO YV O V - YO A AV YO YV AO V O - V O - YV YO YV YO AV O V YO YV YV AV AV -',
  39: 'AV A V AV AV A AV A A',
  40: 'AO O V A AO AO A',
  41: 'O O Y YV A YV YO AO AO -',
  42: 'O YO Y Y -',
  43: 'YV YV Y YV -',
  44: 'V YV YO YO YV Y Y',
  45: 'Y YV Y A AV YV AO AO V A YV A -',
  46: 'AO YO A A AO -',
  47: 'AO YO AO AV A AO',
  48: 'AO AO AO A A AO',
  49: 'V YO YO O Y AV AO AV AV YV YV',
  50: 'YO~ O AV - YO AO AV YO AO~ YV AV A YO',
  51: 'O AO V A A AO',
  52: 'V V YO Y YV AO O Y -',
  53: 'O AV~ A V YV YV~ YO AO AV AO A O Y YO -',
  54: 'AV~ YV AO~ AO~ A A A A YV V -',
  55: 'YV AV V AO A AV -',
  56: 'A YO YO V Y YO Y -',
  57: 'O AV YO AO YO V YV Y YO~ A V AO YO~ YO Y AV~ AV V YO YO -',
  58: 'YO AO YO V Y Y -',
  59: 'O AV O V A A YV -',
  60: 'AV YV O - YV YO O AV A YV A AV A',
};
