// Three-star walkthroughs found by tools/ratkaisija.js, one per level (level number → moves, each held 0.5 s).
// Every one beats its level with at least 95 % of the water and well inside the time limit.
// Y = ylös, A = alas, V = vasen, O = oikea, '-' = leaf level, '~' = half tilt.
// Check them with: pisaraSolver.followAll(PISARA_OHJEET)
window.PISARA_OHJEET = {
  1: 'O Y YO~ Y -',
  2: 'YO YO Y -',
  3: 'AV AV AV AO',
  4: 'YO YO Y -',
  5: 'V AV A A -',
  6: 'YO YO AO AV Y Y AV AV -',
  7: 'YO YO YO Y -',
  8: 'A A AO Y Y YV V',
  9: 'YO YO V Y Y -',
  10: 'O AO AO AV - A AV -',
  11: 'V YV Y Y -',
  12: 'AO AO V A AV AV -',
  13: 'YO YO YO Y',
  14: 'AO O A A -',
  15: 'YO Y YO AV A A AO O',
  16: 'V YV O Y YV YV',
  17: 'AO AO AO A -',
  18: 'YO YV Y Y A - O O -',
  19: 'AO A AO O',
  20: 'YO AO V A AO V AV -',
  21: 'AV AV A -',
  22: 'YO YO Y -',
  23: 'O O YV YO YV O A',
  24: 'YV YV YV Y',
  25: 'AO AO A AO',
  26: 'AO AO A AO',
  27: 'O YO Y Y -',
  28: 'YO YO Y AV V A AV AV YV',
  29: 'AV AV AV A -',
  30: 'YV V Y Y -',
  31: 'YV YV YV Y Y -',
  32: 'YV V Y Y -',
  33: 'AV V - O A - - A V AV A -',
  34: 'V YV Y Y Y',
  35: 'AO AO A AO -',
  36: 'YO O YO Y YO O YO',
  37: 'V YV Y Y -',
  38: 'O AV A YV V YV AO AO YO YO -',
  39: 'AV A V AV AV A AV A A',
  40: 'AO O V A AO AO A',
  41: 'O O Y YV A YV YO AO AO -',
  42: 'O YO Y Y -',
  43: 'YV YV Y YV -',
  44: 'V YV YO YO YV Y Y',
  45: 'Y AV A AV AV V A Y YV O YO',
  46: 'AO YO A A AO -',
  47: 'O~ YV~ A A A AO~ Y O -',
  48: 'AO AO AO A A AO',
  49: 'V YO O - Y AV V YO YO AO AO~ -',
  50: 'YO~ AV~ YO~ AV Y AO O YV A YO V~ YO~ YV Y O A AO',
  51: 'O AO V A YV Y -',
  52: 'V V YO Y YV AO O Y -',
  53: 'O AV~ A V YV YV~ YO AO AV AO A O Y YO -',
  54: 'O~ V AO~ YO V A YO AV~ A YV V A~ AO AV A -',
  55: 'YO~ AV~ AV~ Y AO YO A~ O A~ V AO A -',
  56: 'A YO YO V Y YO Y -',
  57: 'V YO AV YV AV AO A Y YV AV YV AV YV AO V YO AV YO AV AV YO YO YO A V AO YV O O AO A AO',
  58: 'YO AO YO V YO Y Y',
  59: 'AO~ YV AO YV~ - AV~ YO O AV A~ A AV -',
  60: 'AO~ YV~ - AV~ YO YV~ AV YO~ V~ YO Y YO~ Y~ YV YO~ YO YV Y AO AV',
};
